### ISSUE TITLE
Nur n kurze Frage 

### ISSUE THREAD

**Issue by DavidBefort** [RauschRobin/DHBW_Informatik21_Zusammenfassungen#1]
Hey, 

wäre es möglich, dass du deine Datenbanken Zusammenfassung wieder hochlädst. Ich bin Student an einer Hochschule und fande deine Zusammenfassung äußerst gut. 

Vielen dank schon mal im vorraus für eine Rückmeldung

**Comment by RauschRobin** [comment]
Hey,

Ja klar! Ich fixe das Repo gleich heute Abend.
